name: Github-CI
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/ci.yml
  pull_request:
    branches:
    - main
    paths:
      - src/**
      - .github/workflows/ci.yml
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/SVRGN.Libs.Implementations.Service.Persistance.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0.x"

    - name: Restore dependencies
      run: dotnet restore ${{env.SOLUTION}}
      #working-directory: src

    - name: Build
      run: dotnet build ${{env.SOLUTION}} --configuration ${{env.BUILD_CONFIG}} --no-restore
      #working-directory: src

    - name: Run tests
      run: dotnet test ${{env.SOLUTION}} /p:Configuration=${{env.BUILD_CONFIG}} --no-restore --no-build --verbosity normal
      #working-directory: src

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET}}
